### PR TITLE
Add TLV record visibility

### PR DESCRIPTION
**Pull request by jamescridland**
* Adds an ALT tag for the app image
* Adds visibility of the full TLV record, for informational/testing purposes. Click the message to reveal the TLV record.

### CODE REVIEW

**Comment by valcanobacon** [comment]
Showing the underlining TLV is only needed if the UI is not working correctly. I think this is more of a dev/debug feature. Perhaps instead the TLV can be debug logged?

**Comment by jamescridland** [comment]
It already is, in the database.db - but it contains some information that Helipad doesn't currently show (where in the show it was boosted, as one example). As long as it isn't in your face for an ordinary Helipad user, I'd argue that it's no issue being available a click away, personally.

**Comment by valcanobacon** [comment]
You are right there are missing features and this fixes it.. I think I saw a picture of this on NAS, it was a drop down you can click to show the JSON Blog.  I just think we should solve it by implementing the missing features in the UI instead of showing the underlining data structure.

Would be cool if it could queue up the episode to that timestamp and let you listen starting at that point.

**Comment by jamescridland** [comment]
I don't disagree; but this is a quick fix to help those who are interested in what the TLV actually says to be able to see it, without adding complication for the actual user.

(I much prefer debating this with someone who doesn't do so anonymously).

**Comment by ericpp** [comment]
I think #63 took care of this, but let me know if you would like any improvements.

**Pull request closed without merging**
