### PR TITLE
Inject Cargo Version into html

### PR DESCRIPTION
**Pull request by valcanobacon**
One part to solving #18. After this change only the Cargo.toml needs to be updated.

### CODE REVIEW

**Comment by daveajones** [comment]
Excellent!  Will review and merge.

**Review by SpencerPearson — APPROVED** [review]
Nice, this also fixes the Helipad version displayed in the browser moving forward which I had messaged @daveajones about but forgot to formally open an issue about, silly me

**Comment by valcanobacon** [comment]
Fixed merge conflicts

**Comment by daveajones** [comment]
Thanks for the quick fix on this PR.

**Pull request merged**
